import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('node → two local answers → case → JSON/HTML → reload/import and changed CSV', async ({ page, context }) => {
  await page.goto('/')
  await expect(page.getByText('Локальный анализ готов')).toBeVisible()
  await page.getByRole('button', { name: 'Открыть дело расследования' }).click()
  await page.screenshot({ path: 'test-results/case-empty.png', fullPage: true })
  await page.getByRole('button', { name: 'Выбрать первый материал' }).click()
  await page.getByRole('tab', { name: 'Обзор клиента' }).click()
  await page.getByRole('button', { name: 'Добавить узел в дело', exact: true }).click()
  await page.getByRole('tab', { name: /AI Copilot/ }).click()
  for (const prompt of ['Почему этот узел в топе', 'Какой следующий шаг']) {
    await page.getByRole('button', { name: new RegExp(prompt) }).click()
    await page.getByRole('button', { name: /Разобрать вопрос/ }).click()
    await expect(page.getByText('Локальный ответ', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Сохранить ответ в дело' }).click()
  }
  await page.getByRole('button', { name: 'Открыть дело расследования' }).click()
  await expect(page.locator('.case-material')).toHaveCount(3)
  await page.getByLabel('Название дела').fill('Проверка источников и движения средств')
  await page.getByLabel('Что вы проверяете?').fill('Наблюдаемая группа может объединять сбор и дальнейшее распределение средств. Проверить полные выписки и последовательность операций.')
  const note = '<script>window.compromised=true</script>\nЗапросить полную выписку. Сверить контрагентов вне наблюдаемого графа.'
  await page.getByLabel('Ваши наблюдения и вопросы').fill('Запросить полную выписку. Сверить контрагентов вне наблюдаемого графа.\nПроверить, какая часть входящего потока была перечислена дальше в тот же день.')
  await page.getByRole('button', { name: 'Закрыть уведомление' }).click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'test-results/case-populated.png', fullPage: true })
  await page.screenshot({ path: 'test-results/case-populated-viewport.png' })
  await page.getByLabel('Ваши наблюдения и вопросы').fill(note)
  const jsonDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать JSON' }).click()
  const json = readFileSync((await (await jsonDownload).path())!, 'utf8')
  expect(JSON.parse(json).items).toHaveLength(3)
  expect(JSON.parse(json).items[0].gids[0]).toMatch(/^\d{18}$/)

  await page.getByRole('button', { name: 'Удалить материал 2' }).click()
  await expect(page.locator('.case-material')).toHaveCount(2)
  await page.getByRole('button', { name: 'Отменить удаление' }).click()
  await expect(page.locator('.case-material')).toHaveCount(3)
  await page.reload()
  await page.getByRole('button', { name: 'Открыть дело расследования' }).click()
  await expect(page.locator('.case-material')).toHaveCount(3)
  await expect(page.getByLabel('Ваши наблюдения и вопросы')).toHaveValue(note)
  expect(await page.evaluate(() => (window as unknown as { compromised?: boolean }).compromised)).toBeUndefined()

  const htmlDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Печатная справка' }).click()
  const html = readFileSync((await (await htmlDownload).path())!, 'utf8')
  expect(html).toContain('&lt;script&gt;')
  expect(html).not.toContain('<script>')
  const report = await context.newPage()
  await report.setContent(html)
  await report.emulateMedia({ media: 'print' })
  await report.screenshot({ path: 'test-results/case-print.png', fullPage: true })
  await report.screenshot({ path: 'test-results/case-print-viewport.png' })
  await expect(report.locator('footer')).toContainText('Источники относятся к версии')
  expect(await report.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await report.close()

  await page.getByLabel('JSON дела').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{broken') })
  await expect(page.getByRole('alert')).toContainText('Текущее дело не изменено')
  await expect(page.locator('.case-material')).toHaveCount(3)
  await page.getByLabel('JSON дела').setInputFiles({ name: 'case.json', mimeType: 'application/json', buffer: Buffer.from(json) })
  await page.getByRole('button', { name: 'Заменить дело' }).click()
  await expect(page.locator('.case-material')).toHaveCount(3)

  const csv = readFileSync(new URL('../../out/nodes_roles.csv', import.meta.url), 'utf8')
  await page.route('**/out/nodes_roles.csv', route => route.fulfill({ contentType: 'text/csv', body: csv.replace('coordinator', 'transit') }))
  await page.reload()
  await page.getByRole('button', { name: 'Открыть дело расследования' }).click()
  await expect(page.getByText('Снимок другой выгрузки', { exact: true })).toHaveCount(3)
  await expect(page.getByText('Факты сверены с текущими CSV', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/case-stale.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/case-mobile.png', fullPage: true })
  await page.screenshot({ path: 'test-results/case-mobile-viewport.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
